[project]
name = "tinyagent"
version = "0.0"
description = "Very minimal AI agent implementation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.5.0",
    "requests>=2.32.5",
]
